# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

repos:
# Standard hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
    args: ["--allow-multiple-documents"]
  - id: mixed-line-ending
  - id: sort-simple-yaml
  - id: file-contents-sorter
  - id: trailing-whitespace
    files: ^\.github/workflows/|.*\.py$

# Ruff linter, replacement for flake8, pydocstyle, isort
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.14.13'
  hooks:
    - id: ruff-check
      types_or: [ python, pyi ]
      args: [--fix, --show-fixes] # do not run on notebooks
    - id: ruff-format
      types_or: [ python, pyi ]

# CMake formatting
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format
    additional_dependencies: [pyyaml]
    types: [file]
    files: (\.cmake|CMakeLists.txt)(.in)?$
    


# towncrier
- repo: https://github.com/twisted/towncrier
  rev: 25.8.0
  hooks:
    - id: towncrier-check
