#!/usr/bin/env python3
"""Generate docs/migration_v2_layout.md from the live inventories.

The v2 layout guide must not drift from the code it describes, so both
of its tables are generated:

* the settings table from ``MCEq.config.groups.GROUPS`` (the same mapping
  the runtime views use), and
* the import-path table from the shim modules' ``__all__`` / module
  docstrings plus the moved-package registry below.

Run from the repository root:

    python scripts/gen_migration_doc.py

The file is deterministic: no timestamps, iteration in sorted order.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from MCEq.config.groups import GROUPS  # noqa: E402

# Every moved import path a v1 user might type, as (v1 path, v2 home,
# status). "facade" = permanent alias by decision (D-list in the refactor
# plan); "keep" = survives 2.0 (public-usage census); "shim" = importable
# under both names; "removed" = old name deleted at the v2.0 cull.
IMPORT_TABLE = [
    ("MCEq.core.MCEqRun", "MCEq.driver.mceq_run.MCEqRun", "facade"),
    (
        "MCEq.particlemanager.ParticleManager",
        "MCEq.species.manager.ParticleManager",
        "keep",
    ),
    (
        "MCEq.particlemanager.MCEqParticle",
        "MCEq.species.particle.MCEqParticle",
        "shim",
    ),
    (
        "MCEq.geometry.density_profiles",
        "MCEq.environment (base/corsika/isothermal/msis00/msis21/tabulated)",
        "keep",
    ),
    ("MCEq.geometry.geometry", "MCEq.environment.geometry", "keep"),
    (
        "MCEq.geometry.atmosphere_parameters",
        "MCEq.environment.parameters",
        "gone",
    ),
    ("MCEq.geometry.nrlmsise00", "MCEq.environment._ext.nrlmsise00", "keep"),
    ("MCEq.geometry.corsikaatm", "MCEq.environment._ext.corsikaatm", "keep"),
    (
        "MCEq.geometry.EarthsAtmosphere",
        "MCEq.environment.base.EarthsAtmosphere",
        "keep",
    ),
    ("MCEq.geometry.column", "MCEq.environment.column", "removed"),
    ("MCEq.geometry.gtracr_cutoff", "MCEq.environment.geomagnetic.cutoff", "removed"),
    (
        "MCEq.geometry.location_centered",
        "MCEq.environment.location_centered",
        "removed",
    ),
    ("MCEq.geometry.msis21_atmosphere", "MCEq.environment.msis21", "removed"),
    ("MCEq.geometry.nrlmsise00_mceq", "MCEq.environment.msis00_backend", "removed"),
    ("MCEq.geometry.registry", "MCEq.environment.registry", "removed"),
    ("MCEq.ddm", "MCEq.models.ddm.ddm", "removed-rr"),
    ("MCEq.ddm_utils", "MCEq.models.ddm.ddm_utils", "removed"),
    ("MCEq.hankel", "MCEq.driver.results.inverse_hankel_legacy", "removed"),
    ("MCEq.download", "MCEq.data.download", "removed"),
    ("MCEq.secant", "MCEq.operators.secant", "removed"),
    ("MCEq.operator_assembly", "MCEq.operators.compiled", "removed"),
    ("MCEq.spacc", "MCEq.solvers._kernels.spacc", "moved"),
    ("MCEq.etd2_kernels", "MCEq.solvers._kernels.etd2", "moved"),
    ("mceq_config", "MCEq.config", "facade"),
    ("MCEq.misc.EnergyGrid / energy_grid / gen_xmat", "MCEq.data.energy_grid", "shim"),
]

STATUS_NOTE = {
    "facade": "permanent",
    "shim": "importable under both names",
    "keep": "kept at 2.0 (public-usage census)",
    "removed": "removed at 2.0 (public-usage census: no users)",
    "removed-rr": "removed at 2.0 (maintainer re-ruling 2026-09-09)",
    "kept20": "kept at 2.0, removed in the next follow-up release",
    "gone": "removed at 2.0 (M14; census saw no external users)",
    "moved": "old name gone (private module)",
}


def settings_table() -> str:
    rows = [
        "| flat name (v1 spelling, still canonical) | group attribute |",
        "|---|---|",
    ]
    for group in sorted(GROUPS):
        for attr, flat in sorted(GROUPS[group].items(), key=lambda kv: kv[1]):
            rows.append(f"| `{flat}` | `config.{group}.{attr}` |")
    return "\n".join(rows)


def import_table() -> str:
    rows = ["| v1 import path | v2 home | after 2.0 |", "|---|---|---|"]
    for v1, v2, status in sorted(IMPORT_TABLE):
        rows.append(f"| `{v1}` | `{v2}` | {STATUS_NOTE[status]} |")
    return "\n".join(rows)


DOC = f"""# MCEq v2 layout: where everything moved

This file is generated by `scripts/gen_migration_doc.py`; do not edit
it by hand. It lists the two things a v1 user needs: which settings
group now owns each configuration name, and where each import path went.

## Settings

Every v1 flat `MCEq.config` name keeps working unchanged — the flat
names are canonical and silent forever (decision D14/D-3), and v2
additionally organises them into groups on the same module:
`config.grid.e_min` is the same value as `config.e_min`. A run can
also carry a detached snapshot of the whole surface
(`MCEqRun(config=RunConfig.snapshot())`); snapshots are read-only and
isolated from later global writes.

{settings_table()}

`has_mkl`, `has_cuda`, `has_accelerate` stay flat detection facts, not
group members. The legacy `mceq_config` module remains importable as an
alias of `MCEq.config` and disappears at 2.0.

## Import paths

The layered v2 tree (`util -> config -> data -> species -> operators ->
solvers -> driver`, with `environment` and `models` beside it) is the
implementation home of everything below. The paths marked removed at 2.0
no longer import (decision D6 and the release-cut census ruling —
only `MCEq.core` as the import façade and the census-kept shims stay);
the rest keep working under both spellings.

{import_table()}

"Kept at 2.0" and "removed at 2.0" reflect the public-usage census
re-run of 2026-09-09 and the M13 keep-list ruling of the release cut.


## Deprecated names that warn

One genuinely retired API still warns: `MCEqRun.set_theta_deg` (use
`set_zenith_azimuth`, decision D7). `MCEqRun.solve_multirhs` warned through
the 1.x/2.0 development cycle and is now removed at 2.0 (use `solve_batch`
and read `res.sol` / `res.grid_sol`). Flat config access and the kept shim
import paths do not warn (D14 resolution, ruling D-3).
"""


def main() -> None:
    out = Path(__file__).resolve().parent.parent / "docs" / "migration_v2_layout.md"
    out.write_text(DOC)
    print(f"wrote {out} ({len(DOC.splitlines())} lines)")


if __name__ == "__main__":
    main()
