#!/usr/bin/env python3
"""Generate docs/migration_v2_layout.md from the live inventories.

The v2 layout guide must not drift from the code it describes, so both
of its tables are generated:

* the settings table from ``MCEq.config.groups.GROUPS`` (the same mapping
  the runtime views use), and
* the import-path table from the shim modules' ``__all__`` / module
  docstrings plus the moved-package registry below.

Run from the repository root:

    python scripts/gen_migration_doc.py

The file is deterministic: no timestamps, iteration in sorted order.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from MCEq.config.groups import GROUPS  # noqa: E402

# Every moved import path a v1 user might type, as (v1 path, v2 home,
# status). "shim" = importable under both names, deleted at 2.0;
# "facade" = permanent alias by decision (D-list in the refactor plan).
IMPORT_TABLE = [
    ("MCEq.core.MCEqRun", "MCEq.driver.mceq_run.MCEqRun", "facade"),
    (
        "MCEq.particlemanager.ParticleManager",
        "MCEq.species.manager.ParticleManager",
        "shim",
    ),
    ("MCEq.particlemanager.MCEqParticle", "MCEq.species.particle.MCEqParticle", "shim"),
    (
        "MCEq.geometry.density_profiles",
        "MCEq.environment (base/corsika/isothermal/msis00/msis21/tabulated)",
        "shim",
    ),
    ("MCEq.geometry.geometry", "MCEq.environment.geometry", "shim"),
    ("MCEq.geometry.atmosphere_parameters", "MCEq.environment.parameters", "shim"),
    ("MCEq.geometry.nrlmsise00", "MCEq.environment._ext.nrlmsise00", "shim"),
    ("MCEq.geometry.nrlmsise00_mceq", "MCEq.environment.msis00_backend", "shim"),
    ("MCEq.geometry.corsikaatm", "MCEq.environment._ext.corsikaatm", "shim"),
    ("MCEq.geometry.gtracr_cutoff", "MCEq.environment.geomagnetic.cutoff", "shim"),
    ("MCEq.geometry.column", "MCEq.environment.column", "shim"),
    ("MCEq.geometry.location_centered", "MCEq.environment.location_centered", "shim"),
    ("MCEq.geometry.msis21_atmosphere", "MCEq.environment.msis21", "shim"),
    (
        "MCEq.geometry.EarthsAtmosphere",
        "MCEq.environment.base.EarthsAtmosphere",
        "shim",
    ),
    ("MCEq.ddm", "MCEq.models.ddm.ddm", "shim"),
    ("MCEq.ddm_utils", "MCEq.models.ddm.ddm_utils", "shim"),
    ("MCEq.hankel", "MCEq.driver.results.inverse_hankel_legacy", "shim"),
    ("MCEq.download", "MCEq.data.download", "shim"),
    ("MCEq.spacc", "MCEq.solvers.backends.accelerate", "shim"),
    ("MCEq.etd2_kernels", "MCEq.solvers._kernels (M11)", "shim"),
    ("MCEq.secant", "MCEq.operators.secant", "shim"),
    ("MCEq.operator_assembly", "MCEq.operators.matrix_builder", "shim"),
    ("mceq_config", "MCEq.config", "shim"),
    ("MCEq.misc.EnergyGrid / energy_grid / gen_xmat", "MCEq.data.energy_grid", "shim"),
]

STATUS_NOTE = {
    "facade": "permanent",
    "shim": "removed at 2.0",
}


def settings_table() -> str:
    rows = [
        "| flat name (v1 spelling, still canonical) | group attribute |",
        "|---|---|",
    ]
    for group in sorted(GROUPS):
        for attr, flat in sorted(GROUPS[group].items(), key=lambda kv: kv[1]):
            rows.append(f"| `{flat}` | `config.{group}.{attr}` |")
    return "\n".join(rows)


def import_table() -> str:
    rows = ["| v1 import path | v2 home | after 2.0 |", "|---|---|---|"]
    for v1, v2, status in sorted(IMPORT_TABLE):
        rows.append(f"| `{v1}` | `{v2}` | {STATUS_NOTE[status]} |")
    return "\n".join(rows)


DOC = f"""# MCEq v2 layout: where everything moved

This file is generated by `scripts/gen_migration_doc.py`; do not edit
it by hand. It lists the two things a v1 user needs: which settings
group now owns each configuration name, and where each import path went.

## Settings

Every v1 flat `MCEq.config` name keeps working unchanged — the flat
names are canonical and silent forever (decision D14/D-3), and v2
additionally organises them into groups on the same module:
`config.grid.e_min` is the same value as `config.e_min`. A run can
also carry a detached snapshot of the whole surface
(`MCEqRun(config=RunConfig.snapshot())`); snapshots are read-only and
isolated from later global writes.

{settings_table()}

`has_mkl`, `has_cuda`, `has_accelerate` stay flat detection facts, not
group members. The legacy `mceq_config` module remains importable as an
alias of `MCEq.config` and disappears at 2.0.

## Import paths

The layered v2 tree (`util -> config -> data -> species -> operators ->
solvers -> driver`, with `environment` and `models` beside it) is the
implementation home of everything below. The v1 path column keeps
working in v2.x; the 2.0 column marks what is deleted (decision D6 —
only `MCEq.core` as the import façade stays permanently).

{import_table()}

## Deprecated names that warn

Only genuinely retired APIs warn today: `MCEqRun.set_theta_deg` (use
`set_zenith_azimuth`, decision D7) and `MCEqRun.solve_multirhs` (use
`solve_batch`). Flat config access and the shim import paths above do
not warn (D14 resolution, ruling D-3).
"""


def main() -> None:
    out = Path(__file__).resolve().parent.parent / "docs" / "migration_v2_layout.md"
    out.write_text(DOC)
    print(f"wrote {out} ({len(DOC.splitlines())} lines)")


if __name__ == "__main__":
    main()
