name: Test

on:
  pull_request:
    paths:
      - src/**
      - tests/**
      - pyproject.toml
      - CMakeLists.txt
      - .github/workflows/test.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            python-version: "3.12"
            installs: "mkl numpy>=2 scipy matplotlib"

          - os: macos-14
            python-version: "3.12"
            installs: ""

          - os: ubuntu-latest
            python-version: "3.13"
            installs: "mkl"
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: False
        fetch-depth: 3
    - uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.job }}-${{ matrix.os }}-${{ matrix.python-version }}
    - uses: astral-sh/setup-uv@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - run: uv pip install --system . pytest pytest-xdist ${{ matrix.installs }}
    - run: pytest -n 3